# Generated by Django 5.1.1 on 2024-09-12 15:12

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cartorderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmn0123456789', length=6, max_length=20, prefix=''),
        ),
    ]
