# Generated by Django 5.1.1 on 2024-09-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cartorder_coupons_alter_cartorder_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='saved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
