# Generated by Django 5.1.1 on 2024-09-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cartorder_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('New Order', 'New Order'), ('New Review', 'New Review'), ('New Course Question', 'New Course Question'), ('Course Published', 'Course Published'), ('Course Enrollment Completed', 'Course Enrollment Completed')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course-file'),
        ),
    ]
