# Generated by Django 5.1.1 on 2024-09-14 16:47

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=6, max_length=20, prefix='', unique=True),
        ),
    ]
